DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `name` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `city` varchar(255),
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `users` (`name`,`email`,`city`)
VALUES
  ("Kenneth Aguilar","kennethaguilar7041@protonmail.edu","Ratlam"),
  ("Ingrid Baker","ingridbaker@protonmail.org","Daman"),
  ("Stacey Mercado","staceymercado@outlook.edu","Belgaum"),
  ("Vladimir Evans","vladimirevans@hotmail.couk","Achalpur"),
  ("Pandora Stevens","pandorastevens756@protonmail.couk","Korba"),
  ("Keelie Roach","keelieroach5833@protonmail.com","Purulia"),
  ("Venus Carroll","venuscarroll5937@aol.org","Itanagar"),
  ("Olga Carpenter","olgacarpenter@aol.org","Cuttack"),
  ("Channing Lawson","channinglawson3339@google.com","Kavaratti"),
  ("Morgan Shaw","morganshaw@aol.org","Dewas"),
  ("Laith Finch","laithfinch2751@protonmail.ca","Kavaratti"),
  ("Judith Kerr","judithkerr@hotmail.edu","Gangtok"),
  ("Randall Randall","randallrandall291@aol.com","Bharuch"),
  ("Stuart Saunders","stuartsaunders3456@google.net","Silvassa"),
  ("Louis Hurley","louishurley@protonmail.edu","Faridabad"),
  ("Cade Vaughn","cadevaughn9967@icloud.edu","Damoh"),
  ("Timon Garrison","timongarrison7244@hotmail.net","Chandigarh"),
  ("Lunea Nolan","luneanolan934@aol.com","Itanagar"),
  ("Holly Mcmahon","hollymcmahon1589@protonmail.com","Panjim"),
  ("Chancellor Reid","chancellorreid5812@protonmail.com","Bhubaneswar"),
  ("Britanney Benton","britanneybenton@google.ca","Sambalpur"),
  ("Avram Howe","avramhowe1547@google.ca","Bokaro Steel City"),
  ("Caleb Bruce","calebbruce@yahoo.com","Dera Ghazi Khan"),
  ("Gary Schultz","garyschultz@protonmail.org","Kavaratti"),
  ("Audra Velazquez","audravelazquez@protonmail.com","Delhi"),
  ("Adele Hamilton","adelehamilton@yahoo.ca","Brahmapur"),
  ("Michelle Dejesus","michelledejesus@google.edu","Ahmadpur East"),
  ("Odysseus Burton","odysseusburton3382@yahoo.com","Itanagar"),
  ("Macy Compton","macycompton@aol.edu","Pondicherry"),
  ("Alden Reyes","aldenreyes@outlook.couk","Delhi"),
  ("Kato Farrell","katofarrell5877@icloud.org","Delhi"),
  ("Garth Hanson","garthhanson2307@protonmail.couk","Davangere"),
  ("Xander Valenzuela","xandervalenzuela7833@yahoo.couk","Thalassery"),
  ("Amber Blake","amberblake@hotmail.org","Shillong"),
  ("Brett Glover","brettglover3330@protonmail.com","Chandigarh"),
  ("Maya Santiago","mayasantiago1896@aol.couk","Kohima"),
  ("Harriet Moses","harrietmoses8351@protonmail.com","Srinagar"),
  ("Nerea Nguyen","nereanguyen@google.com","Gangtok"),
  ("Herman Hernandez","hermanhernandez@aol.ca","Haridwar"),
  ("Lavinia Waller","laviniawaller67@google.com","Silvassa"),
  ("Petra Morris","petramorris@hotmail.net","Itanagar"),
  ("Beau Clark","beauclark@yahoo.edu","Jodhpur"),
  ("Carson Haney","carsonhaney@protonmail.couk","Banda"),
  ("Brenden Forbes","brendenforbes@yahoo.org","Shimla"),
  ("Gannon Page","gannonpage@outlook.com","Shillong"),
  ("Aileen Martinez","aileenmartinez@outlook.com","Thalassery"),
  ("Unity Cochran","unitycochran@outlook.net","Dehradun"),
  ("Armando Mueller","armandomueller@hotmail.couk","Rajapalaiyam"),
  ("Tiger Frye","tigerfrye2361@hotmail.net","Kavaratti"),
  ("Fay Salazar","faysalazar@google.net","Gurgaon");
